Написать на PyTorch forward и backward полносвязного слоя без использования autograd.
Написать 1-2 адаптивных оптимизатора.
Решить задачу нахождения корней квадратного уравнения методом градиентного спуска.

In [1]:
import torch
import torch.nn as nn

In [2]:
tensor = torch.tensor([1, 2, 3, 4, 5]).float()
wieghts = nn.Parameter(torch.rand(5), requires_grad=True)

print(tensor)
print(wieghts)
# tensor = tensor.detach()
# tensor.detach_()

linear = wieghts @ tensor.t()

activation = nn.ReLU()

activated_linear = activation(linear) # torch.relu(linear)

linear = nn.Linear(5, 1, bias=True)
linear(tensor)

tensor([1., 2., 3., 4., 5.])
Parameter containing:
tensor([0.5086, 0.6228, 0.0398, 0.4587, 0.0283], requires_grad=True)


tensor([-0.5356], grad_fn=<AddBackward0>)

In [3]:
#TODO реализовать forward и backward
class CustomLinear(nn.Module):
    def __init__(self,
                 input_dim : int,
                 hidden_dim : int,
                 out_dim : int,
                  *args, **kwargs):
        super().__init__()
        self.l1 = nn.Linear(input_dim,hidden_dim,bias=True)
        self.l2 = nn.Linear(hidden_dim,hidden_dim,bias=True)
        self.l3 = nn.Linear(hidden_dim,out_dim,bias=True)

    def forward(self, x):
        x = nn.ReLU(self.l1(x))
        x = nn.ReLU(self.l2(x))
        x = self.l3(x)
        return x

    def backward(self, grad):
        pass

net = CustomLinear()
print(net)

# seq = nn.Sequential(
#     {
#         'linear1': nn.Linear(5, 1, bias=True),
#         'relu1': nn.ReLU(),
#         'linear2': nn.Linear(5, 1, bias=True),
#         'relu2': nn.ReLU(),
#         'linear3': nn.Linear(5, 1, bias=True),
#         'relu3': nn.ReLU(),
#     }
# )

# predict = seq(tensor)
# loss = torch.mean((target - predict) ** 2)
# loss.backward()



CustomLinear(
  (l1): Linear(in_features=5, out_features=10, bias=True)
  (l2): Linear(in_features=10, out_features=10, bias=True)
  (l3): Linear(in_features=10, out_features=5, bias=True)
)


In [13]:
# Решить задачу нахождения корней квадратного уравнения методом градиентного спуска.
a, b, c = 1, -2, 1

func = lambda x: (a*x**2 + b*x + c)
gradient = lambda x: (2*a*x + b)
h = 0.01

def solver(x_start):
    x = x_start
    for i in range(1000):
        x -= h * gradient(x)
        if abs(func(x)) < 0.0000000001:
            print('i = ',i)
            return x, i
    print(func(x))
    print(x)
    
print(solver(1000))

i =  911
(1.0000099482460874, 911)
